### PR TITLE
Fix footnote styling

### PR DESCRIPTION
**Pull request by salim-b**
## Summary

Fixes styling of footnotes. The affected CSS rule caused the `<sup>` element from footnote references to be unclickable and have a line break before it.

Note that I have no clue what purpose the affected CSS rule was originally intended to serve.

## Motivation

Fix footnotes in content.

## Checks

- [x] Read [Create a Pull Request](https://gethyas.com/docs/contributing/how-to-contribute/#create-a-pull-request)
- [x] Supports all screen sizes (if relevant)
- [x] Supports both light and dark mode (if relevant)
- [ ] Passes `npm run test`

### CODE REVIEW

**Comment by h-enk** [comment]
> Note that I have no clue what purpose the affected CSS rule was originally intended to serve.

It's for positioning the footnote link when clicking the footnote backlink (correction for sticky navbar).

Without it — the footnote link is hidden beneath the (sticky) navbar:

Snag_a019f6

With it — it's visible:

Snag_a04c31

I'll re-add it

**Comment by h-enk** [comment]
3169e972f99ee866d45b83a5a55f47e5fb2d681f

**Comment by salim-b** [comment]
> I'll re-add it

But you added the exact same rule as this PR removed? 🤨

Did you test the rule with actual footnote content?

The problem I referred to is content like the following paragraph:

```md
Some paragraph with a footnote reference[^1] in the middle.

[^1]: A footnote.
```

This paragraph is split (line wrap) after "reference" in the rendered HTML.

**Comment by salim-b** [comment]
Plus: the problem your CSS rule is intended to solve applies to *all* links, not just footnotes, right? So I guess the `sup` CSS selector is not what we want to leverage here, but `a` instead. No?

**Comment by h-enk** [comment]
> This paragraph is split (line wrap) after "reference" in the rendered HTML.

Ah, I didn't get that — I see now

Snag_4811f3

**Comment by h-enk** [comment]
> Plus: the problem your CSS rule is intended to solve applies to _all_ anchor links (fragment identifiers), not just footnotes, right? So I guess the `sup` CSS selector is not what we want to leverage here, but `a` instead. No?

Only `<sup>` elements with an `id` attribute are affected. So something like `Y = X<sup>2</sup>` not:

Snag_4ce5da

**Comment by h-enk** [comment]
Will look into a fix

**Comment by h-enk** [comment]
This is way more elegant (just a oneliner) and robust :

```scss
sup[id] {
  scroll-margin-top: 5rem; 
}
```

Reources: [One line CSS solution to prevent anchor links from scrolling behind a sticky or fixed header](https://getpublii.com/blog/one-line-css-solution-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header.html)

**Comment by salim-b** [comment]
> This is way more elegant (just a oneliner) and robust

Awesome, thank you! I didn't know about [`scroll-margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin) until now.

**Comment by h-enk** [comment]
> Awesome, thank you! I didn't know about [`scroll-margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin) until now.

Me neither 😄

**Pull request merged**
